### ISSUE TITLE
Need better documentation for devise integration

### ISSUE THREAD

**Issue by m5rk** [madzhuga/rails_workflow#8]
This gem makes implicit assumptions that it would be helpful to document; e.g.,

https://github.com/madzhuga/rails_workflow/blob/master/app/decorators/rails_workflow/operation_template_decorator.rb#L45-L46

```ruby
    def assignment
      [
          ::User.role_text(object.role),
          ::User.group_text(object.group)
      ].compact.join(", ")
    end
```

This assumes the `User` model has `.role_text` and `.group_text` class methods that operate as expected.

**Comment by madzhuga** [comment]
@m5rk, you right. This need to be documented (will check shortly).

My only assumption was that 
user roles / groups will be set using gem symbolize:
```ruby
class User < ActiveRecord::Base
  symbolize :role, in: [:admin, :customer, :sale, :stock]
end
```
this symoblize will also create following methods:
user.role_text
User.get_role_values

Would like to know your comment on that - may be you have some better ideas ;)

**Comment by samnissen** [comment]
Is this why I'm getting 

```ruby
NoMethodError - undefined method `role_text' for #<Class:0x0000010dcd7540>:
  activerecord (4.2.1) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  rails_workflow (0.3.4) app/decorators/rails_workflow/operation_template_decorator.rb:45:in `assignment'
  # ...
```

?

**Comment by madzhuga** [comment]
@samnissen because operation template decorator (for user operations) expects to have role_text method on user. Please check my comment above - about symbolize roles. Take a look at 

https://github.com/madzhuga/rails_workflow/blob/master/spec/dummy/app/models/user.rb

it includes
```ruby
include RailsWorkflow::User::Assignment
```
and example def self.get_role_values method in case if you don't want to use symbolise with roles list for some reason.
